/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ui.tests;

import com.google.inject.Injector;
import githubwf.githubwf.ui.internal.GithubwfActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class NormalJobContainerOneOf1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GithubwfActivator.getInstance().getInjector("githubwf.githubwf.NormalJobContainerOneOf1");
	}

}
