/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import githubwf.githubwf.ConfigurationOneOf0RuntimeModule;
import githubwf.githubwf.ConfigurationOneOf0StandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConfigurationOneOf0IdeSetup extends ConfigurationOneOf0StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConfigurationOneOf0RuntimeModule(), new ConfigurationOneOf0IdeModule()));
	}
	
}
