/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ide;


/**
 * Use this class to register ide components.
 */
public class ConfigurationOneOf3IdeModule extends AbstractConfigurationOneOf3IdeModule {
}
