/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide;


/**
 * Use this class to register ide components.
 */
public class EnvOneOf0AdditionalPropertiesOneOf1IdeModule extends AbstractEnvOneOf0AdditionalPropertiesOneOf1IdeModule {
}
