/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import githubwf.githubwf.EnvOneOf0AdditionalPropertiesOneOf0RuntimeModule;
import githubwf.githubwf.EnvOneOf0AdditionalPropertiesOneOf0StandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EnvOneOf0AdditionalPropertiesOneOf0IdeSetup extends EnvOneOf0AdditionalPropertiesOneOf0StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EnvOneOf0AdditionalPropertiesOneOf0RuntimeModule(), new EnvOneOf0AdditionalPropertiesOneOf0IdeModule()));
	}
	
}
