/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide;


/**
 * Use this class to register ide components.
 */
public class NormalJobRuns_45onOneOf1IdeModule extends AbstractNormalJobRuns_45onOneOf1IdeModule {
}
