/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide;


/**
 * Use this class to register ide components.
 */
public class NormalJobEnvironmentOneOf0IdeModule extends AbstractNormalJobEnvironmentOneOf0IdeModule {
}
