/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ide;


/**
 * Use this class to register ide components.
 */
public class NormalJobStrategyMatrixOneOf0IdeModule extends AbstractNormalJobStrategyMatrixOneOf0IdeModule {
}
