/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ide;


/**
 * Use this class to register ide components.
 */
public class NormalJobStrategyMatrixOneOf1IdeModule extends AbstractNormalJobStrategyMatrixOneOf1IdeModule {
}
