/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf3RuntimeModule;
import githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf3StandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class NormalJobRuns_45onOneOf1AnyOf3IdeSetup extends NormalJobRuns_45onOneOf1AnyOf3StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new NormalJobRuns_45onOneOf1AnyOf3RuntimeModule(), new NormalJobRuns_45onOneOf1AnyOf3IdeModule()));
	}
	
}
