/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import githubwf.githubwf.PermissionsOneOf1RuntimeModule;
import githubwf.githubwf.PermissionsOneOf1StandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PermissionsOneOf1IdeSetup extends PermissionsOneOf1StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PermissionsOneOf1RuntimeModule(), new PermissionsOneOf1IdeModule()));
	}
	
}
