/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ide;


/**
 * Use this class to register ide components.
 */
public class RefOneOf0AllOf1IdeModule extends AbstractRefOneOf0AllOf1IdeModule {
}
