/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1IfAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("githubwf/githubwf/parser/antlr/internal/InternalGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1IfParser.tokens");
	}
}
