/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf0ScopeProvider extends DelegatingScopeProvider {
}
