/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import githubwf.githubwf.ide.contentassist.antlr.internal.InternalGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Parser;
import githubwf.githubwf.services.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractAccess().getAlternatives(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getEDoubleObjectAccess().getAlternatives(), "rule__EDoubleObject__Alternatives");
			builder.put(grammarAccess.getEBooleanObjectAccess().getAlternatives(), "rule__EBooleanObject__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives(), "rule__EDouble__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAccess().getGroup(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject__Group__0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAccess().getGroup_2(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject__Group_2__0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAccess().getGroup_2_1(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject__Group_2_1__0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAccess().getGroup(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray__Group__0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAccess().getGroup_2(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray__Group_2__0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAccess().getGroup_2_1(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray__Group_2_1__0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesAccess().getGroup(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties__Group__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup(), "rule__ArrayValue__Group__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup_2(), "rule__ArrayValue__Group_2__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup_2_1(), "rule__ArrayValue__Group_2_1__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup(), "rule__ObjectValue__Group__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup_2(), "rule__ObjectValue__Group_2__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup_2_1(), "rule__ObjectValue__Group_2_1__0");
			builder.put(grammarAccess.getKeyValuePairAccess().getGroup(), "rule__KeyValuePair__Group__0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Access().getPatternProperties0Assignment(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1__PatternProperties0Assignment");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringAccess().getPatternProperties0Assignment(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString__PatternProperties0Assignment");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerAccess().getPatternProperties0Assignment(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger__PatternProperties0Assignment");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberAccess().getPatternProperties0Assignment(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber__PatternProperties0Assignment");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanAccess().getPatternProperties0Assignment(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean__PatternProperties0Assignment");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAccess().getPatternProperties0Assignment_2_0(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject__PatternProperties0Assignment_2_0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAccess().getPatternProperties0Assignment_2_1_1(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject__PatternProperties0Assignment_2_1_1");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAccess().getPatternProperties0Assignment_2_0(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray__PatternProperties0Assignment_2_0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAccess().getPatternProperties0Assignment_2_1_1(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray__PatternProperties0Assignment_2_1_1");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullAccess().getPatternProperties0Assignment(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull__PatternProperties0Assignment");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesAccess().getKeyAssignment_0(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties__KeyAssignment_0");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesAccess().getAdditionalPropertiesAssignment_2(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties__AdditionalPropertiesAssignment_2");
			builder.put(grammarAccess.getJsonDocumentAccess().getValueAssignment(), "rule__JsonDocument__ValueAssignment");
			builder.put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
			builder.put(grammarAccess.getArrayValueAccess().getValueAssignment_2_0(), "rule__ArrayValue__ValueAssignment_2_0");
			builder.put(grammarAccess.getArrayValueAccess().getValueAssignment_2_1_1(), "rule__ArrayValue__ValueAssignment_2_1_1");
			builder.put(grammarAccess.getNullValueAccess().getValueAssignment(), "rule__NullValue__ValueAssignment");
			builder.put(grammarAccess.getNumberValueAccess().getValueAssignment(), "rule__NumberValue__ValueAssignment");
			builder.put(grammarAccess.getObjectValueAccess().getKeyvaluepairAssignment_2_0(), "rule__ObjectValue__KeyvaluepairAssignment_2_0");
			builder.put(grammarAccess.getObjectValueAccess().getKeyvaluepairAssignment_2_1_1(), "rule__ObjectValue__KeyvaluepairAssignment_2_1_1");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
			builder.put(grammarAccess.getKeyValuePairAccess().getKeyAssignment_0(), "rule__KeyValuePair__KeyAssignment_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getValueAssignment_2(), "rule__KeyValuePair__ValueAssignment_2");
			builder.put(grammarAccess.getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsAccess().getItemsAssignment(), "rule__GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items__ItemsAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess grammarAccess;

	@Override
	protected InternalGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Parser createParser() {
		InternalGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Parser result = new InternalGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
