/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import githubwf.githubwf.ide.contentassist.antlr.internal.InternalNormalJobStepsItemsAllOf1Parser;
import githubwf.githubwf.services.NormalJobStepsItemsAllOf1GrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class NormalJobStepsItemsAllOf1Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(NormalJobStepsItemsAllOf1GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, NormalJobStepsItemsAllOf1GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1PropertiesAbstractAccess().getAlternatives(), "rule__NormalJobStepsItemsAllOf1PropertiesAbstract__Alternatives");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfAbstractAccess().getAlternatives(), "rule__NormalJobStepsItemsAllOf1IfAbstract__Alternatives");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorAbstractAccess().getAlternatives(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorAbstract__Alternatives");
			builder.put(grammarAccess.getShellAbstractAccess().getAlternatives(), "rule__ShellAbstract__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getEnvAbstractAccess().getAlternatives(), "rule__EnvAbstract__Alternatives");
			builder.put(grammarAccess.getEBooleanObjectAccess().getAlternatives(), "rule__EBooleanObject__Alternatives");
			builder.put(grammarAccess.getEDoubleObjectAccess().getAlternatives(), "rule__EDoubleObject__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives(), "rule__EDouble__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getVALID_STRINGAccess().getAlternatives(), "rule__VALID_STRING__Alternatives");
			builder.put(grammarAccess.getKEYWORDAccess().getAlternatives(), "rule__KEYWORD__Alternatives");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Access().getGroup(), "rule__NormalJobStepsItemsAllOf1__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Access().getGroup_2(), "rule__NormalJobStepsItemsAllOf1__Group_2__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Access().getGroup_2_1(), "rule__NormalJobStepsItemsAllOf1__Group_2_1__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IdAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Id__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1NameAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Name__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1UsesAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Uses__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1RunAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Run__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Working_45directoryAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Working_45directory__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1ShellAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Shell__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1WithAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1With__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1EnvAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Env__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Timeout_45minutesAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Timeout_45minutes__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfTypeBooleanAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1IfTypeBoolean__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfTypeNumberAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1IfTypeNumber__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfTypeStringAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1IfTypeString__Group__0");
			builder.put(grammarAccess.getShellTypeObjectAccess().getGroup(), "rule__ShellTypeObject__Group__0");
			builder.put(grammarAccess.getShellTypeObjectAccess().getGroup_2(), "rule__ShellTypeObject__Group_2__0");
			builder.put(grammarAccess.getShellTypeObjectAccess().getGroup_2_1(), "rule__ShellTypeObject__Group_2_1__0");
			builder.put(grammarAccess.getShellTypeArrayAccess().getGroup(), "rule__ShellTypeArray__Group__0");
			builder.put(grammarAccess.getShellTypeArrayAccess().getGroup_2(), "rule__ShellTypeArray__Group_2__0");
			builder.put(grammarAccess.getShellTypeArrayAccess().getGroup_2_1(), "rule__ShellTypeArray__Group_2_1__0");
			builder.put(grammarAccess.getShellAdditionalPropertiesAccess().getGroup(), "rule__ShellAdditionalProperties__Group__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup(), "rule__ArrayValue__Group__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup_2(), "rule__ArrayValue__Group_2__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup_2_1(), "rule__ArrayValue__Group_2_1__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup(), "rule__ObjectValue__Group__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup_2(), "rule__ObjectValue__Group_2__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup_2_1(), "rule__ObjectValue__Group_2_1__0");
			builder.put(grammarAccess.getKeyValuePairAccess().getGroup(), "rule__KeyValuePair__Group__0");
			builder.put(grammarAccess.getEnvTypeObjectAccess().getGroup(), "rule__EnvTypeObject__Group__0");
			builder.put(grammarAccess.getEnvTypeObjectAccess().getGroup_2(), "rule__EnvTypeObject__Group_2__0");
			builder.put(grammarAccess.getEnvTypeObjectAccess().getGroup_2_1(), "rule__EnvTypeObject__Group_2_1__0");
			builder.put(grammarAccess.getEnvTypeArrayAccess().getGroup(), "rule__EnvTypeArray__Group__0");
			builder.put(grammarAccess.getEnvTypeArrayAccess().getGroup_2(), "rule__EnvTypeArray__Group_2__0");
			builder.put(grammarAccess.getEnvTypeArrayAccess().getGroup_2_1(), "rule__EnvTypeArray__Group_2_1__0");
			builder.put(grammarAccess.getEnvAdditionalPropertiesAccess().getGroup(), "rule__EnvAdditionalProperties__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeStringAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeString__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeIntegerAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeInteger__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeNumberAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeNumber__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeBooleanAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeBoolean__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeObjectAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeObject__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeObjectAccess().getGroup_4(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeObject__Group_4__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeObjectAccess().getGroup_4_1(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeObject__Group_4_1__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeArrayAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeArray__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeArrayAccess().getGroup_4(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeArray__Group_4__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeArrayAccess().getGroup_4_1(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeArray__Group_4_1__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeNullAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeNull__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorAdditionalPropertiesAccess().getGroup(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorAdditionalProperties__Group__0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Access().getItemsAssignment_2_0(), "rule__NormalJobStepsItemsAllOf1__ItemsAssignment_2_0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Access().getItemsAssignment_2_1_1(), "rule__NormalJobStepsItemsAllOf1__ItemsAssignment_2_1_1");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IdAccess().getIdAssignment_2(), "rule__NormalJobStepsItemsAllOf1Id__IdAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfAccess().getIf_Assignment(), "rule__NormalJobStepsItemsAllOf1If__If_Assignment");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1NameAccess().getNameAssignment_3(), "rule__NormalJobStepsItemsAllOf1Name__NameAssignment_3");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1UsesAccess().getUsesAssignment_2(), "rule__NormalJobStepsItemsAllOf1Uses__UsesAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1RunAccess().getRunAssignment_2(), "rule__NormalJobStepsItemsAllOf1Run__RunAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Working_45directoryAccess().getWorking_45directoryAssignment_2(), "rule__NormalJobStepsItemsAllOf1Working_45directory__Working_45directoryAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1ShellAccess().getShellAssignment_2(), "rule__NormalJobStepsItemsAllOf1Shell__ShellAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1WithAccess().getWithAssignment_2(), "rule__NormalJobStepsItemsAllOf1With__WithAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1EnvAccess().getEnvAssignment_2(), "rule__NormalJobStepsItemsAllOf1Env__EnvAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorAccess().getContinue_45on_45errorAssignment(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45error__Continue_45on_45errorAssignment");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Timeout_45minutesAccess().getTimeout_45minutesAssignment_2(), "rule__NormalJobStepsItemsAllOf1Timeout_45minutes__Timeout_45minutesAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfTypeBooleanAccess().getIf_Assignment_2(), "rule__NormalJobStepsItemsAllOf1IfTypeBoolean__If_Assignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfTypeNumberAccess().getIf_Assignment_2(), "rule__NormalJobStepsItemsAllOf1IfTypeNumber__If_Assignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1IfTypeStringAccess().getIf_Assignment_2(), "rule__NormalJobStepsItemsAllOf1IfTypeString__If_Assignment_2");
			builder.put(grammarAccess.getWorking_45directoryAccess().getWorking_45directoryAssignment(), "rule__Working_45directory__Working_45directoryAssignment");
			builder.put(grammarAccess.getShellAccess().getShellAssignment(), "rule__Shell__ShellAssignment");
			builder.put(grammarAccess.getShellTypeStringAccess().getShellAssignment(), "rule__ShellTypeString__ShellAssignment");
			builder.put(grammarAccess.getShellTypeIntegerAccess().getShellAssignment(), "rule__ShellTypeInteger__ShellAssignment");
			builder.put(grammarAccess.getShellTypeNumberAccess().getShellAssignment(), "rule__ShellTypeNumber__ShellAssignment");
			builder.put(grammarAccess.getShellTypeBooleanAccess().getShellAssignment(), "rule__ShellTypeBoolean__ShellAssignment");
			builder.put(grammarAccess.getShellTypeObjectAccess().getShellAssignment_2_0(), "rule__ShellTypeObject__ShellAssignment_2_0");
			builder.put(grammarAccess.getShellTypeObjectAccess().getShellAssignment_2_1_1(), "rule__ShellTypeObject__ShellAssignment_2_1_1");
			builder.put(grammarAccess.getShellTypeArrayAccess().getShellAssignment_2_0(), "rule__ShellTypeArray__ShellAssignment_2_0");
			builder.put(grammarAccess.getShellTypeArrayAccess().getShellAssignment_2_1_1(), "rule__ShellTypeArray__ShellAssignment_2_1_1");
			builder.put(grammarAccess.getShellTypeNullAccess().getShellAssignment(), "rule__ShellTypeNull__ShellAssignment");
			builder.put(grammarAccess.getShellAdditionalPropertiesAccess().getKeyAssignment_0(), "rule__ShellAdditionalProperties__KeyAssignment_0");
			builder.put(grammarAccess.getShellAdditionalPropertiesAccess().getAdditionalPropertiesAssignment_2(), "rule__ShellAdditionalProperties__AdditionalPropertiesAssignment_2");
			builder.put(grammarAccess.getJsonDocumentAccess().getValueAssignment(), "rule__JsonDocument__ValueAssignment");
			builder.put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
			builder.put(grammarAccess.getArrayValueAccess().getValueAssignment_2_0(), "rule__ArrayValue__ValueAssignment_2_0");
			builder.put(grammarAccess.getArrayValueAccess().getValueAssignment_2_1_1(), "rule__ArrayValue__ValueAssignment_2_1_1");
			builder.put(grammarAccess.getNullValueAccess().getValueAssignment(), "rule__NullValue__ValueAssignment");
			builder.put(grammarAccess.getNumberValueAccess().getValueAssignment(), "rule__NumberValue__ValueAssignment");
			builder.put(grammarAccess.getObjectValueAccess().getKeyvaluepairAssignment_2_0(), "rule__ObjectValue__KeyvaluepairAssignment_2_0");
			builder.put(grammarAccess.getObjectValueAccess().getKeyvaluepairAssignment_2_1_1(), "rule__ObjectValue__KeyvaluepairAssignment_2_1_1");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
			builder.put(grammarAccess.getKeyValuePairAccess().getKeyAssignment_0(), "rule__KeyValuePair__KeyAssignment_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getValueAssignment_2(), "rule__KeyValuePair__ValueAssignment_2");
			builder.put(grammarAccess.getShellItemsAccess().getItemsAssignment(), "rule__ShellItems__ItemsAssignment");
			builder.put(grammarAccess.getEnvAccess().getEnvAssignment(), "rule__Env__EnvAssignment");
			builder.put(grammarAccess.getEnvTypeStringAccess().getEnvAssignment(), "rule__EnvTypeString__EnvAssignment");
			builder.put(grammarAccess.getEnvTypeIntegerAccess().getEnvAssignment(), "rule__EnvTypeInteger__EnvAssignment");
			builder.put(grammarAccess.getEnvTypeNumberAccess().getEnvAssignment(), "rule__EnvTypeNumber__EnvAssignment");
			builder.put(grammarAccess.getEnvTypeBooleanAccess().getEnvAssignment(), "rule__EnvTypeBoolean__EnvAssignment");
			builder.put(grammarAccess.getEnvTypeObjectAccess().getEnvAssignment_2_0(), "rule__EnvTypeObject__EnvAssignment_2_0");
			builder.put(grammarAccess.getEnvTypeObjectAccess().getEnvAssignment_2_1_1(), "rule__EnvTypeObject__EnvAssignment_2_1_1");
			builder.put(grammarAccess.getEnvTypeArrayAccess().getEnvAssignment_2_0(), "rule__EnvTypeArray__EnvAssignment_2_0");
			builder.put(grammarAccess.getEnvTypeArrayAccess().getEnvAssignment_2_1_1(), "rule__EnvTypeArray__EnvAssignment_2_1_1");
			builder.put(grammarAccess.getEnvTypeNullAccess().getEnvAssignment(), "rule__EnvTypeNull__EnvAssignment");
			builder.put(grammarAccess.getEnvAdditionalPropertiesAccess().getKeyAssignment_0(), "rule__EnvAdditionalProperties__KeyAssignment_0");
			builder.put(grammarAccess.getEnvAdditionalPropertiesAccess().getAdditionalPropertiesAssignment_2(), "rule__EnvAdditionalProperties__AdditionalPropertiesAssignment_2");
			builder.put(grammarAccess.getEnvItemsAccess().getItemsAssignment(), "rule__EnvItems__ItemsAssignment");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeStringAccess().getContinue_45on_45errorAssignment_2(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeString__Continue_45on_45errorAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeIntegerAccess().getContinue_45on_45errorAssignment_2(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeInteger__Continue_45on_45errorAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeNumberAccess().getContinue_45on_45errorAssignment_2(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeNumber__Continue_45on_45errorAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeBooleanAccess().getContinue_45on_45errorAssignment_2(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeBoolean__Continue_45on_45errorAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeObjectAccess().getContinue_45on_45errorAssignment_4_0(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeObject__Continue_45on_45errorAssignment_4_0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeObjectAccess().getContinue_45on_45errorAssignment_4_1_1(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeObject__Continue_45on_45errorAssignment_4_1_1");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeArrayAccess().getContinue_45on_45errorAssignment_4_0(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeArray__Continue_45on_45errorAssignment_4_0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeArrayAccess().getContinue_45on_45errorAssignment_4_1_1(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeArray__Continue_45on_45errorAssignment_4_1_1");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorTypeNullAccess().getContinue_45on_45errorAssignment_2(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorTypeNull__Continue_45on_45errorAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorAdditionalPropertiesAccess().getKeyAssignment_0(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorAdditionalProperties__KeyAssignment_0");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorAdditionalPropertiesAccess().getAdditionalPropertiesAssignment_2(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorAdditionalProperties__AdditionalPropertiesAssignment_2");
			builder.put(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorItemsAccess().getItemsAssignment(), "rule__NormalJobStepsItemsAllOf1Continue_45on_45errorItems__ItemsAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private NormalJobStepsItemsAllOf1GrammarAccess grammarAccess;

	@Override
	protected InternalNormalJobStepsItemsAllOf1Parser createParser() {
		InternalNormalJobStepsItemsAllOf1Parser result = new InternalNormalJobStepsItemsAllOf1Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public NormalJobStepsItemsAllOf1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NormalJobStepsItemsAllOf1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
