/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import githubwf.githubwf.ide.contentassist.antlr.internal.InternalRefOneOf0AllOf0Parser;
import githubwf.githubwf.services.RefOneOf0AllOf0GrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class RefOneOf0AllOf0Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RefOneOf0AllOf0GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RefOneOf0AllOf0GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRefOneOf0AllOf0AbstractAccess().getAlternatives(), "rule__RefOneOf0AllOf0Abstract__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getEDoubleObjectAccess().getAlternatives(), "rule__EDoubleObject__Alternatives");
			builder.put(grammarAccess.getEBooleanObjectAccess().getAlternatives(), "rule__EBooleanObject__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives(), "rule__EDouble__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeObjectAccess().getGroup(), "rule__RefOneOf0AllOf0TypeObject__Group__0");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeObjectAccess().getGroup_2(), "rule__RefOneOf0AllOf0TypeObject__Group_2__0");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeObjectAccess().getGroup_2_1(), "rule__RefOneOf0AllOf0TypeObject__Group_2_1__0");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeArrayAccess().getGroup(), "rule__RefOneOf0AllOf0TypeArray__Group__0");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeArrayAccess().getGroup_2(), "rule__RefOneOf0AllOf0TypeArray__Group_2__0");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeArrayAccess().getGroup_2_1(), "rule__RefOneOf0AllOf0TypeArray__Group_2_1__0");
			builder.put(grammarAccess.getRefOneOf0AllOf0AdditionalPropertiesAccess().getGroup(), "rule__RefOneOf0AllOf0AdditionalProperties__Group__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup(), "rule__ArrayValue__Group__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup_2(), "rule__ArrayValue__Group_2__0");
			builder.put(grammarAccess.getArrayValueAccess().getGroup_2_1(), "rule__ArrayValue__Group_2_1__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup(), "rule__ObjectValue__Group__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup_2(), "rule__ObjectValue__Group_2__0");
			builder.put(grammarAccess.getObjectValueAccess().getGroup_2_1(), "rule__ObjectValue__Group_2_1__0");
			builder.put(grammarAccess.getKeyValuePairAccess().getGroup(), "rule__KeyValuePair__Group__0");
			builder.put(grammarAccess.getRefOneOf0AllOf0Access().getRefAssignment(), "rule__RefOneOf0AllOf0__RefAssignment");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeStringAccess().getRefAssignment(), "rule__RefOneOf0AllOf0TypeString__RefAssignment");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeIntegerAccess().getRefAssignment(), "rule__RefOneOf0AllOf0TypeInteger__RefAssignment");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeNumberAccess().getRefAssignment(), "rule__RefOneOf0AllOf0TypeNumber__RefAssignment");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeBooleanAccess().getRefAssignment(), "rule__RefOneOf0AllOf0TypeBoolean__RefAssignment");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeObjectAccess().getRefAssignment_2_0(), "rule__RefOneOf0AllOf0TypeObject__RefAssignment_2_0");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeObjectAccess().getRefAssignment_2_1_1(), "rule__RefOneOf0AllOf0TypeObject__RefAssignment_2_1_1");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeArrayAccess().getRefAssignment_2_0(), "rule__RefOneOf0AllOf0TypeArray__RefAssignment_2_0");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeArrayAccess().getRefAssignment_2_1_1(), "rule__RefOneOf0AllOf0TypeArray__RefAssignment_2_1_1");
			builder.put(grammarAccess.getRefOneOf0AllOf0TypeNullAccess().getRefAssignment(), "rule__RefOneOf0AllOf0TypeNull__RefAssignment");
			builder.put(grammarAccess.getRefOneOf0AllOf0AdditionalPropertiesAccess().getKeyAssignment_0(), "rule__RefOneOf0AllOf0AdditionalProperties__KeyAssignment_0");
			builder.put(grammarAccess.getRefOneOf0AllOf0AdditionalPropertiesAccess().getAdditionalPropertiesAssignment_2(), "rule__RefOneOf0AllOf0AdditionalProperties__AdditionalPropertiesAssignment_2");
			builder.put(grammarAccess.getJsonDocumentAccess().getValueAssignment(), "rule__JsonDocument__ValueAssignment");
			builder.put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
			builder.put(grammarAccess.getArrayValueAccess().getValueAssignment_2_0(), "rule__ArrayValue__ValueAssignment_2_0");
			builder.put(grammarAccess.getArrayValueAccess().getValueAssignment_2_1_1(), "rule__ArrayValue__ValueAssignment_2_1_1");
			builder.put(grammarAccess.getNullValueAccess().getValueAssignment(), "rule__NullValue__ValueAssignment");
			builder.put(grammarAccess.getNumberValueAccess().getValueAssignment(), "rule__NumberValue__ValueAssignment");
			builder.put(grammarAccess.getObjectValueAccess().getKeyvaluepairAssignment_2_0(), "rule__ObjectValue__KeyvaluepairAssignment_2_0");
			builder.put(grammarAccess.getObjectValueAccess().getKeyvaluepairAssignment_2_1_1(), "rule__ObjectValue__KeyvaluepairAssignment_2_1_1");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
			builder.put(grammarAccess.getKeyValuePairAccess().getKeyAssignment_0(), "rule__KeyValuePair__KeyAssignment_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getValueAssignment_2(), "rule__KeyValuePair__ValueAssignment_2");
			builder.put(grammarAccess.getRefOneOf0AllOf0ItemsAccess().getItemsAssignment(), "rule__RefOneOf0AllOf0Items__ItemsAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RefOneOf0AllOf0GrammarAccess grammarAccess;

	@Override
	protected InternalRefOneOf0AllOf0Parser createParser() {
		InternalRefOneOf0AllOf0Parser result = new InternalRefOneOf0AllOf0Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RefOneOf0AllOf0GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RefOneOf0AllOf0GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
