/*
 * generated by Xtext 2.29.0
 */
parser grammar InternalNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Parser;

options {
	tokenVocab=InternalNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Lexer;
	superClass=AbstractInternalContentAssistParser;
}

@header {
package githubwf.githubwf.ide.contentassist.antlr.internal;
import java.util.Map;
import java.util.HashMap;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import githubwf.githubwf.services.NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0GrammarAccess;

}
@members {
	private NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0GrammarAccess grammarAccess;
	private final Map<String, String> tokenNameToValue = new HashMap<String, String>();
	
	{
		tokenNameToValue.put("Colon", "':'");
		tokenNameToValue.put("True", "'true'");
		tokenNameToValue.put("False", "'false'");
		tokenNameToValue.put("ContinueOnError", "'\"continue-on-error\"'");
	}

	public void setGrammarAccess(NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		String result = tokenNameToValue.get(tokenName);
		if (result == null)
			result = tokenName;
		return result;
	}
}

// Entry rule entryRuleNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0
entryRuleNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0
:
{ before(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Rule()); }
	 ruleNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0
{ after(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Rule()); } 
	 EOF 
;

// Rule NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0
ruleNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getGroup()); }
		(rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__0)
		{ after(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEBooleanObject
entryRuleEBooleanObject
:
{ before(grammarAccess.getEBooleanObjectRule()); }
	 ruleEBooleanObject
{ after(grammarAccess.getEBooleanObjectRule()); } 
	 EOF 
;

// Rule EBooleanObject
ruleEBooleanObject 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEBooleanObjectAccess().getAlternatives()); }
		(rule__EBooleanObject__Alternatives)
		{ after(grammarAccess.getEBooleanObjectAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleKEYWORD
entryRuleKEYWORD
:
{ before(grammarAccess.getKEYWORDRule()); }
	 ruleKEYWORD
{ after(grammarAccess.getKEYWORDRule()); } 
	 EOF 
;

// Rule KEYWORD
ruleKEYWORD 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getKEYWORDAccess().getContinueOnErrorKeyword()); }
		ContinueOnError
		{ after(grammarAccess.getKEYWORDAccess().getContinueOnErrorKeyword()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EBooleanObject__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEBooleanObjectAccess().getTrueKeyword_0()); }
		True
		{ after(grammarAccess.getEBooleanObjectAccess().getTrueKeyword_0()); }
	)
	|
	(
		{ before(grammarAccess.getEBooleanObjectAccess().getFalseKeyword_1()); }
		False
		{ after(grammarAccess.getEBooleanObjectAccess().getFalseKeyword_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__0__Impl
	rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getContinueOnErrorKeyword_0()); }
	ContinueOnError
	{ after(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getContinueOnErrorKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__1__Impl
	rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getColonKeyword_1()); }
	Colon
	{ after(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getColonKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getContinue_45on_45errorAssignment_2()); }
	(rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Continue_45on_45errorAssignment_2)
	{ after(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getContinue_45on_45errorAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0__Continue_45on_45errorAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getContinue_45on_45errorEBooleanObjectParserRuleCall_2_0()); }
		ruleEBooleanObject
		{ after(grammarAccess.getNormalJobStepsItemsAllOf1Continue_45on_45errorOneOf0Access().getContinue_45on_45errorEBooleanObjectParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}
