/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1");
		private final Assignment cPatternProperties0Assignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractParserRuleCall_0 = (RuleCall)cPatternProperties0Assignment.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1:
		//	patternProperties0=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract;
		@Override public ParserRule getRule() { return rule; }
		
		////EReference is not a keyword
		//patternProperties0=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract
		public Assignment getPatternProperties0Assignment() { return cPatternProperties0Assignment; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract
		public RuleCall getPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractParserRuleCall_0() { return cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractParserRuleCall_0; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract:
		//	=> GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber |
		//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString |
		//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger |
		//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean |
		//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject |
		//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray |
		//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull;
		@Override public ParserRule getRule() { return rule; }
		
		//=> GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber |
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString |
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger |
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean |
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject |
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray |
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//=> GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberParserRuleCall_0() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberParserRuleCall_0; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringParserRuleCall_1() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringParserRuleCall_1; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerParserRuleCall_2() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerParserRuleCall_2; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanParserRuleCall_3() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanParserRuleCall_3; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectParserRuleCall_4() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectParserRuleCall_4; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayParserRuleCall_5() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayParserRuleCall_5; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullParserRuleCall_6() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullParserRuleCall_6; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract");
		private final RuleCall cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract:
		//	=> GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties;
		@Override public ParserRule getRule() { return rule; }
		
		//=> GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties
		public RuleCall getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesParserRuleCall() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesParserRuleCall; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cArrayValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNullValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNumberValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cObjectValueParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cBooleanValueParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Value jsonMM::Value:
		//	StringValue | ArrayValue | NullValue | NumberValue | ObjectValue | BooleanValue;
		@Override public ParserRule getRule() { return rule; }
		
		//StringValue | ArrayValue | NullValue | NumberValue | ObjectValue | BooleanValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringValue
		public RuleCall getStringValueParserRuleCall_0() { return cStringValueParserRuleCall_0; }
		
		//ArrayValue
		public RuleCall getArrayValueParserRuleCall_1() { return cArrayValueParserRuleCall_1; }
		
		//NullValue
		public RuleCall getNullValueParserRuleCall_2() { return cNullValueParserRuleCall_2; }
		
		//NumberValue
		public RuleCall getNumberValueParserRuleCall_3() { return cNumberValueParserRuleCall_3; }
		
		//ObjectValue
		public RuleCall getObjectValueParserRuleCall_4() { return cObjectValueParserRuleCall_4; }
		
		//BooleanValue
		public RuleCall getBooleanValueParserRuleCall_5() { return cBooleanValueParserRuleCall_5; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString");
		private final Assignment cPatternProperties0Assignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPatternProperties0EStringParserRuleCall_0 = (RuleCall)cPatternProperties0Assignment.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString:
		//	patternProperties0=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//patternProperties0=EString
		public Assignment getPatternProperties0Assignment() { return cPatternProperties0Assignment; }
		
		//EString
		public RuleCall getPatternProperties0EStringParserRuleCall_0() { return cPatternProperties0EStringParserRuleCall_0; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger");
		private final Assignment cPatternProperties0Assignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPatternProperties0EDoubleObjectParserRuleCall_0 = (RuleCall)cPatternProperties0Assignment.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger:
		//	patternProperties0=EDoubleObject;
		@Override public ParserRule getRule() { return rule; }
		
		//patternProperties0=EDoubleObject
		public Assignment getPatternProperties0Assignment() { return cPatternProperties0Assignment; }
		
		//EDoubleObject
		public RuleCall getPatternProperties0EDoubleObjectParserRuleCall_0() { return cPatternProperties0EDoubleObjectParserRuleCall_0; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber");
		private final Assignment cPatternProperties0Assignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPatternProperties0EDoubleObjectParserRuleCall_0 = (RuleCall)cPatternProperties0Assignment.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber:
		//	patternProperties0=EDoubleObject;
		@Override public ParserRule getRule() { return rule; }
		
		//patternProperties0=EDoubleObject
		public Assignment getPatternProperties0Assignment() { return cPatternProperties0Assignment; }
		
		//EDoubleObject
		public RuleCall getPatternProperties0EDoubleObjectParserRuleCall_0() { return cPatternProperties0EDoubleObjectParserRuleCall_0; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean");
		private final Assignment cPatternProperties0Assignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPatternProperties0EBooleanObjectParserRuleCall_0 = (RuleCall)cPatternProperties0Assignment.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean:
		//	patternProperties0=EBooleanObject;
		@Override public ParserRule getRule() { return rule; }
		
		//patternProperties0=EBooleanObject
		public Assignment getPatternProperties0Assignment() { return cPatternProperties0Assignment; }
		
		//EBooleanObject
		public RuleCall getPatternProperties0EBooleanObjectParserRuleCall_0() { return cPatternProperties0EBooleanObjectParserRuleCall_0; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cPatternProperties0Assignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractParserRuleCall_2_0_0 = (RuleCall)cPatternProperties0Assignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cPatternProperties0Assignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractParserRuleCall_2_1_1_0 = (RuleCall)cPatternProperties0Assignment_2_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject:
		//	{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject}
		//	//EReference is not a keyword
		//	'{' (patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract (","
		//	patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract)*)? '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject} //EReference is not a keyword
		//'{' (patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract (","
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract)*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject}
		public Action getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAction_0() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAction_0; }
		
		////EReference is not a keyword
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract (","
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract
		public Assignment getPatternProperties0Assignment_2_0() { return cPatternProperties0Assignment_2_0; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract
		public RuleCall getPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractParserRuleCall_2_0_0() { return cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractParserRuleCall_2_0_0; }
		
		//("," patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract)*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract
		public Assignment getPatternProperties0Assignment_2_1_1() { return cPatternProperties0Assignment_2_1_1; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract
		public RuleCall getPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractParserRuleCall_2_1_1_0() { return cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractParserRuleCall_2_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cPatternProperties0Assignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsParserRuleCall_2_0_0 = (RuleCall)cPatternProperties0Assignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cPatternProperties0Assignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsParserRuleCall_2_1_1_0 = (RuleCall)cPatternProperties0Assignment_2_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray:
		//	{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray}
		//	//EReference is not a keyword
		//	'[' (patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items (","
		//	patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items)*)? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray} //EReference is not a keyword
		//'[' (patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items (","
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items)*)? ']'
		public Group getGroup() { return cGroup; }
		
		//{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray}
		public Action getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAction_0() { return cGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAction_0; }
		
		////EReference is not a keyword
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//(patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items (","
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items
		public Assignment getPatternProperties0Assignment_2_0() { return cPatternProperties0Assignment_2_0; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items
		public RuleCall getPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsParserRuleCall_2_0_0() { return cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsParserRuleCall_2_0_0; }
		
		//("," patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items)*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items
		public Assignment getPatternProperties0Assignment_2_1_1() { return cPatternProperties0Assignment_2_1_1; }
		
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items
		public RuleCall getPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsParserRuleCall_2_1_1_0() { return cPatternProperties0GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsParserRuleCall_2_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull");
		private final Assignment cPatternProperties0Assignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPatternProperties0NullValueParserRuleCall_0 = (RuleCall)cPatternProperties0Assignment.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull:
		//	patternProperties0=NullValue;
		@Override public ParserRule getRule() { return rule; }
		
		////EReference is not a keyword
		//patternProperties0=NullValue
		public Assignment getPatternProperties0Assignment() { return cPatternProperties0Assignment; }
		
		//NullValue
		public RuleCall getPatternProperties0NullValueParserRuleCall_0() { return cPatternProperties0NullValueParserRuleCall_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.EString");
		private final RuleCall cVALID_STRINGParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EString:
		//	VALID_STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//VALID_STRING
		public RuleCall getVALID_STRINGParserRuleCall() { return cVALID_STRINGParserRuleCall; }
	}
	public class EDoubleObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.EDoubleObject");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cE_INTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cE_DOUBLETerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EDoubleObject ecore::EDoubleObject:
		//	E_INT | E_DOUBLE;
		@Override public ParserRule getRule() { return rule; }
		
		//E_INT | E_DOUBLE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//E_INT
		public RuleCall getE_INTTerminalRuleCall_0() { return cE_INTTerminalRuleCall_0; }
		
		//E_DOUBLE
		public RuleCall getE_DOUBLETerminalRuleCall_1() { return cE_DOUBLETerminalRuleCall_1; }
	}
	public class EBooleanObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.EBooleanObject");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBooleanObject ecore::EBooleanObject:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeyEStringParserRuleCall_0_0 = (RuleCall)cKeyAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAdditionalPropertiesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAdditionalPropertiesJsonDocumentParserRuleCall_2_0 = (RuleCall)cAdditionalPropertiesAssignment_2.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties:
		//	key=EString
		//	':'
		//	//EReference is not a keyword
		//	additionalProperties=JsonDocument;
		@Override public ParserRule getRule() { return rule; }
		
		////KeyValue
		//key=EString ':' //EReference is not a keyword
		//additionalProperties=JsonDocument
		public Group getGroup() { return cGroup; }
		
		////KeyValue
		//key=EString
		public Assignment getKeyAssignment_0() { return cKeyAssignment_0; }
		
		//EString
		public RuleCall getKeyEStringParserRuleCall_0_0() { return cKeyEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		////EReference is not a keyword
		//additionalProperties=JsonDocument
		public Assignment getAdditionalPropertiesAssignment_2() { return cAdditionalPropertiesAssignment_2; }
		
		//JsonDocument
		public RuleCall getAdditionalPropertiesJsonDocumentParserRuleCall_2_0() { return cAdditionalPropertiesJsonDocumentParserRuleCall_2_0; }
	}
	public class JsonDocumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.JsonDocument");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueValueParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		////EClass JsonDocument
		//JsonDocument jsonMM::JsonDocument:
		//	value=Value;
		@Override public ParserRule getRule() { return rule; }
		
		////EReference is not a keyword
		//value=Value
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_0() { return cValueValueParserRuleCall_0; }
	}
	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.StringValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		////EClass StringValue
		//StringValue jsonMM::StringValue:
		//	value=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//value=EString
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_0() { return cValueEStringParserRuleCall_0; }
	}
	public class ArrayValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.ArrayValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArrayValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cValueValueParserRuleCall_2_0_0 = (RuleCall)cValueAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cValueAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cValueValueParserRuleCall_2_1_1_0 = (RuleCall)cValueAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		////EClass ArrayValue
		//ArrayValue jsonMM::ArrayValue:
		//	{jsonMM::ArrayValue}
		//	//EReference is not a keyword
		//	'[' (value+=Value ("," value+=Value)*)? ']';
		@Override public ParserRule getRule() { return rule; }
		
		//{jsonMM::ArrayValue} //EReference is not a keyword
		//'[' (value+=Value ("," value+=Value)*)? ']'
		public Group getGroup() { return cGroup; }
		
		//{jsonMM::ArrayValue}
		public Action getArrayValueAction_0() { return cArrayValueAction_0; }
		
		////EReference is not a keyword
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//(value+=Value ("," value+=Value)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//value+=Value
		public Assignment getValueAssignment_2_0() { return cValueAssignment_2_0; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_2_0_0() { return cValueValueParserRuleCall_2_0_0; }
		
		//("," value+=Value)*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//value+=Value
		public Assignment getValueAssignment_2_1_1() { return cValueAssignment_2_1_1; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_2_1_1_0() { return cValueValueParserRuleCall_2_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	public class NullValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.NullValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueNullEnumEnumRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		////EClass NullValue
		//NullValue jsonMM::NullValue:
		//	value=NullEnum;
		@Override public ParserRule getRule() { return rule; }
		
		//value=NullEnum
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//NullEnum
		public RuleCall getValueNullEnumEnumRuleCall_0() { return cValueNullEnumEnumRuleCall_0; }
	}
	public class NumberValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.NumberValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEDoubleParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		////EClass NumberValue
		//NumberValue jsonMM::NumberValue:
		//	value=EDouble;
		@Override public ParserRule getRule() { return rule; }
		
		//value=EDouble
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_0() { return cValueEDoubleParserRuleCall_0; }
	}
	public class ObjectValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.ObjectValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cObjectValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cKeyvaluepairAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cKeyvaluepairKeyValuePairParserRuleCall_2_0_0 = (RuleCall)cKeyvaluepairAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cKeyvaluepairAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cKeyvaluepairKeyValuePairParserRuleCall_2_1_1_0 = (RuleCall)cKeyvaluepairAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		////EClass ObjectValue
		//ObjectValue jsonMM::ObjectValue:
		//	{jsonMM::ObjectValue}
		//	'{' (keyvaluepair+=KeyValuePair ("," keyvaluepair+=KeyValuePair)*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{jsonMM::ObjectValue} '{' (keyvaluepair+=KeyValuePair ("," keyvaluepair+=KeyValuePair)*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{jsonMM::ObjectValue}
		public Action getObjectValueAction_0() { return cObjectValueAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(keyvaluepair+=KeyValuePair ("," keyvaluepair+=KeyValuePair)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//keyvaluepair+=KeyValuePair
		public Assignment getKeyvaluepairAssignment_2_0() { return cKeyvaluepairAssignment_2_0; }
		
		//KeyValuePair
		public RuleCall getKeyvaluepairKeyValuePairParserRuleCall_2_0_0() { return cKeyvaluepairKeyValuePairParserRuleCall_2_0_0; }
		
		//("," keyvaluepair+=KeyValuePair)*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//keyvaluepair+=KeyValuePair
		public Assignment getKeyvaluepairAssignment_2_1_1() { return cKeyvaluepairAssignment_2_1_1; }
		
		//KeyValuePair
		public RuleCall getKeyvaluepairKeyValuePairParserRuleCall_2_1_1_0() { return cKeyvaluepairKeyValuePairParserRuleCall_2_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class BooleanValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.BooleanValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEBooleanParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		////EClass BooleanValue
		//BooleanValue jsonMM::BooleanValue:
		//	value=EBoolean;
		@Override public ParserRule getRule() { return rule; }
		
		//value=EBoolean
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_0() { return cValueEBooleanParserRuleCall_0; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.EDouble");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cE_INTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cE_DOUBLETerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EDouble ecore::EDouble:
		//	E_INT | E_DOUBLE;
		@Override public ParserRule getRule() { return rule; }
		
		//E_INT | E_DOUBLE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//E_INT
		public RuleCall getE_INTTerminalRuleCall_0() { return cE_INTTerminalRuleCall_0; }
		
		//E_DOUBLE
		public RuleCall getE_DOUBLETerminalRuleCall_1() { return cE_DOUBLETerminalRuleCall_1; }
	}
	public class KeyValuePairElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.KeyValuePair");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeyEStringParserRuleCall_0_0 = (RuleCall)cKeyAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		////EClass KeyValuePair
		//KeyValuePair jsonMM::KeyValuePair:
		//	key=EString
		//	':'
		//	//EReference is not a keyword
		//	value=Value;
		@Override public ParserRule getRule() { return rule; }
		
		////KeyValue
		//key=EString ':' //EReference is not a keyword
		//value=Value
		public Group getGroup() { return cGroup; }
		
		////KeyValue
		//key=EString
		public Assignment getKeyAssignment_0() { return cKeyAssignment_0; }
		
		//EString
		public RuleCall getKeyEStringParserRuleCall_0_0() { return cKeyEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		////EReference is not a keyword
		//value=Value
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_2_0() { return cValueValueParserRuleCall_2_0; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items");
		private final Assignment cItemsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cItemsJsonDocumentParserRuleCall_0 = (RuleCall)cItemsAssignment.eContents().get(0);
		
		////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items
		//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items:
		//	items=JsonDocument;
		@Override public ParserRule getRule() { return rule; }
		
		////EReference is not a keyword
		//items=JsonDocument
		public Assignment getItemsAssignment() { return cItemsAssignment; }
		
		//JsonDocument
		public RuleCall getItemsJsonDocumentParserRuleCall_0() { return cItemsJsonDocumentParserRuleCall_0; }
	}
	public class VALID_STRINGElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.VALID_STRING");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//VALID_STRING:
		//	STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	
	public class NullEnumElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.NullEnum");
		private final EnumLiteralDeclaration cNullEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cNullNullKeyword_0 = (Keyword)cNullEnumLiteralDeclaration.eContents().get(0);
		
		//enum NullEnum returns jsonMM::NullEnum:
		//	null;
		public EnumRule getRule() { return rule; }
		
		//null
		public EnumLiteralDeclaration getNullEnumLiteralDeclaration() { return cNullEnumLiteralDeclaration; }
		
		//'null'
		public Keyword getNullNullKeyword_0() { return cNullNullKeyword_0; }
	}
	
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Elements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract;
	private final ValueElements pValue;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull;
	private final EStringElements pEString;
	private final EDoubleObjectElements pEDoubleObject;
	private final EBooleanObjectElements pEBooleanObject;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties;
	private final JsonDocumentElements pJsonDocument;
	private final StringValueElements pStringValue;
	private final ArrayValueElements pArrayValue;
	private final NullValueElements pNullValue;
	private final NumberValueElements pNumberValue;
	private final ObjectValueElements pObjectValue;
	private final BooleanValueElements pBooleanValue;
	private final NullEnumElements eNullEnum;
	private final EDoubleElements pEDouble;
	private final KeyValuePairElements pKeyValuePair;
	private final EBooleanElements pEBoolean;
	private final GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsElements pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items;
	private final TerminalRule tINT;
	private final VALID_STRINGElements pVALID_STRING;
	private final TerminalRule tSTRING;
	private final TerminalRule tE_INT;
	private final TerminalRule tE_DOUBLE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1 = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Elements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractElements();
		this.pValue = new ValueElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullElements();
		this.pEString = new EStringElements();
		this.pEDoubleObject = new EDoubleObjectElements();
		this.pEBooleanObject = new EBooleanObjectElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesElements();
		this.pJsonDocument = new JsonDocumentElements();
		this.pStringValue = new StringValueElements();
		this.pArrayValue = new ArrayValueElements();
		this.pNullValue = new NullValueElements();
		this.pNumberValue = new NumberValueElements();
		this.pObjectValue = new ObjectValueElements();
		this.pBooleanValue = new BooleanValueElements();
		this.eNullEnum = new NullEnumElements();
		this.pEDouble = new EDoubleElements();
		this.pKeyValuePair = new KeyValuePairElements();
		this.pEBoolean = new EBooleanElements();
		this.pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items = new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsElements();
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.INT");
		this.pVALID_STRING = new VALID_STRINGElements();
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.STRING");
		this.tE_INT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.E_INT");
		this.tE_DOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1.E_DOUBLE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("githubwf.githubwf.GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1:
	//	patternProperties0=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Elements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Access() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Rule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Access().getRule();
	}
	
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract:
	//	=> GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber |
	//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString |
	//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger |
	//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean |
	//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject |
	//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray |
	//	GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Abstract;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AbstractAccess().getRule();
	}
	
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract:
	//	=> GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstractAccess().getRule();
	}
	
	//Value jsonMM::Value:
	//	StringValue | ArrayValue | NullValue | NumberValue | ObjectValue | BooleanValue;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString:
	//	patternProperties0=EString;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeString;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeStringAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger:
	//	patternProperties0=EDoubleObject;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeInteger;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeIntegerAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber:
	//	patternProperties0=EDoubleObject;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumber;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNumberAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean:
	//	patternProperties0=EBooleanObject;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBoolean;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeBooleanAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject:
	//	{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject}
	//	//EReference is not a keyword
	//	'{' (patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract (","
	//	patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1PropertiesAbstract)*)? '}';
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObject;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeObjectAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray:
	//	{GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray}
	//	//EReference is not a keyword
	//	'[' (patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items (","
	//	patternProperties0+=GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items)*)? ']';
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArray;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeArrayAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull:
	//	patternProperties0=NullValue;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNull;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1TypeNullAccess().getRule();
	}
	
	//EString:
	//	VALID_STRING;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EDoubleObject ecore::EDoubleObject:
	//	E_INT | E_DOUBLE;
	public EDoubleObjectElements getEDoubleObjectAccess() {
		return pEDoubleObject;
	}
	
	public ParserRule getEDoubleObjectRule() {
		return getEDoubleObjectAccess().getRule();
	}
	
	//EBooleanObject ecore::EBooleanObject:
	//	'true' | 'false';
	public EBooleanObjectElements getEBooleanObjectAccess() {
		return pEBooleanObject;
	}
	
	public ParserRule getEBooleanObjectRule() {
		return getEBooleanObjectAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties:
	//	key=EString
	//	':'
	//	//EReference is not a keyword
	//	additionalProperties=JsonDocument;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalProperties;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1AdditionalPropertiesAccess().getRule();
	}
	
	////EClass JsonDocument
	//JsonDocument jsonMM::JsonDocument:
	//	value=Value;
	public JsonDocumentElements getJsonDocumentAccess() {
		return pJsonDocument;
	}
	
	public ParserRule getJsonDocumentRule() {
		return getJsonDocumentAccess().getRule();
	}
	
	////EClass StringValue
	//StringValue jsonMM::StringValue:
	//	value=EString;
	public StringValueElements getStringValueAccess() {
		return pStringValue;
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}
	
	////EClass ArrayValue
	//ArrayValue jsonMM::ArrayValue:
	//	{jsonMM::ArrayValue}
	//	//EReference is not a keyword
	//	'[' (value+=Value ("," value+=Value)*)? ']';
	public ArrayValueElements getArrayValueAccess() {
		return pArrayValue;
	}
	
	public ParserRule getArrayValueRule() {
		return getArrayValueAccess().getRule();
	}
	
	////EClass NullValue
	//NullValue jsonMM::NullValue:
	//	value=NullEnum;
	public NullValueElements getNullValueAccess() {
		return pNullValue;
	}
	
	public ParserRule getNullValueRule() {
		return getNullValueAccess().getRule();
	}
	
	////EClass NumberValue
	//NumberValue jsonMM::NumberValue:
	//	value=EDouble;
	public NumberValueElements getNumberValueAccess() {
		return pNumberValue;
	}
	
	public ParserRule getNumberValueRule() {
		return getNumberValueAccess().getRule();
	}
	
	////EClass ObjectValue
	//ObjectValue jsonMM::ObjectValue:
	//	{jsonMM::ObjectValue}
	//	'{' (keyvaluepair+=KeyValuePair ("," keyvaluepair+=KeyValuePair)*)?
	//	'}';
	public ObjectValueElements getObjectValueAccess() {
		return pObjectValue;
	}
	
	public ParserRule getObjectValueRule() {
		return getObjectValueAccess().getRule();
	}
	
	////EClass BooleanValue
	//BooleanValue jsonMM::BooleanValue:
	//	value=EBoolean;
	public BooleanValueElements getBooleanValueAccess() {
		return pBooleanValue;
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//enum NullEnum returns jsonMM::NullEnum:
	//	null;
	public NullEnumElements getNullEnumAccess() {
		return eNullEnum;
	}
	
	public EnumRule getNullEnumRule() {
		return getNullEnumAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	E_INT | E_DOUBLE;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	////EClass KeyValuePair
	//KeyValuePair jsonMM::KeyValuePair:
	//	key=EString
	//	':'
	//	//EReference is not a keyword
	//	value=Value;
	public KeyValuePairElements getKeyValuePairAccess() {
		return pKeyValuePair;
	}
	
	public ParserRule getKeyValuePairRule() {
		return getKeyValuePairAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	////EClass GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items
	//GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items:
	//	items=JsonDocument;
	public GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsElements getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsAccess() {
		return pGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1Items;
	}
	
	public ParserRule getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsRule() {
		return getGithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1ItemsAccess().getRule();
	}
	
	//@Override
	//terminal INT returns ecore::EInt:
	//	'0' | '1'..'9' '0'..'9'*;
	public TerminalRule getINTRule() {
		return tINT;
	}
	
	//VALID_STRING:
	//	STRING;
	public VALID_STRINGElements getVALID_STRINGAccess() {
		return pVALID_STRING;
	}
	
	public ParserRule getVALID_STRINGRule() {
		return getVALID_STRINGAccess().getRule();
	}
	
	//@Override
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"';
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal E_INT:
	//	'-'? INT;
	public TerminalRule getE_INTRule() {
		return tE_INT;
	}
	
	//terminal E_DOUBLE:
	//	'-'? INT ('.' INT+)? (('E' | 'e') ('+' | '-')? INT)?;
	public TerminalRule getE_DOUBLERule() {
		return tE_DOUBLE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
