/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.formatting2

import com.google.inject.Inject
import githubwf.githubwf.services.ReusableWorkflowCallJobConcurrencyOneOf0GrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2

class ReusableWorkflowCallJobConcurrencyOneOf0Formatter extends AbstractFormatter2 {
	
	@Inject extension ReusableWorkflowCallJobConcurrencyOneOf0GrammarAccess
	
	// TODO: implement for 
}
