/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GithubwfRootJobsPatternProperties0OneOf1UiModule extends AbstractGithubwfRootJobsPatternProperties0OneOf1UiModule {

	public GithubwfRootJobsPatternProperties0OneOf1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
