/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NormalJobContainerOneOf1UiModule extends AbstractNormalJobContainerOneOf1UiModule {

	public NormalJobContainerOneOf1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
