/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NormalJobStepsItemsAllOf0OneOf0UiModule extends AbstractNormalJobStepsItemsAllOf0OneOf0UiModule {

	public NormalJobStepsItemsAllOf0OneOf0UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
