/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NormalJobConcurrencyOneOf1UiModule extends AbstractNormalJobConcurrencyOneOf1UiModule {

	public NormalJobConcurrencyOneOf1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
