/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NormalJobRuns_45onOneOf1AnyOf0UiModule extends AbstractNormalJobRuns_45onOneOf1AnyOf0UiModule {

	public NormalJobRuns_45onOneOf1AnyOf0UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
