/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ShellAnyOf1UiModule extends AbstractShellAnyOf1UiModule {

	public ShellAnyOf1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
