/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ContainerPortsItemsOneOf1ProposalProvider extends AbstractContainerPortsItemsOneOf1ProposalProvider {
}
