/**
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.formatting2;

import com.google.inject.Inject;
import githubwf.githubwf.services.ConfigurationOneOf0GrammarAccess;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class ConfigurationOneOf0Formatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ConfigurationOneOf0GrammarAccess _configurationOneOf0GrammarAccess;
}
