/**
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf.formatting2;

import com.google.inject.Inject;
import githubwf.Configuration;
import githubwf.ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0;
import githubwf.ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items;
import githubwf.githubwf.services.ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0GrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Formatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0GrammarAccess _reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0GrammarAccess;

  protected void _format(final ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0 reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, @Extension final IFormattableDocument document) {
    EList<ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items> _additionalProperties = reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0.getAdditionalProperties();
    for (final ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items : _additionalProperties) {
      document.<ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items>format(reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items);
    }
  }

  protected void _format(final ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items, @Extension final IFormattableDocument document) {
    document.<Configuration>format(reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items.getItems());
  }

  public void format(final Object reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, final IFormattableDocument document) {
    if (reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0 instanceof XtextResource) {
      _format((XtextResource)reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, document);
      return;
    } else if (reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0 instanceof ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0) {
      _format((ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0)reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, document);
      return;
    } else if (reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0 instanceof ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items) {
      _format((ReusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0Items)reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, document);
      return;
    } else if (reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0 instanceof EObject) {
      _format((EObject)reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, document);
      return;
    } else if (reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0 == null) {
      _format((Void)null, document);
      return;
    } else if (reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0 != null) {
      _format(reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(reusableWorkflowCallJobStrategyMatrixAdditionalPropertiesOneOf0, document).toString());
    }
  }
}
