/*
 * generated by Xtext 2.29.0
 */
parser grammar InternalNormalJobRuns_45onOneOf1AnyOf4Parser;

options {
	tokenVocab=InternalNormalJobRuns_45onOneOf1AnyOf4Lexer;
	superClass=AbstractInternalAntlrParser;
}

@header {
package githubwf.githubwf.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import githubwf.githubwf.services.NormalJobRuns_45onOneOf1AnyOf4GrammarAccess;

}

@members {

 	private NormalJobRuns_45onOneOf1AnyOf4GrammarAccess grammarAccess;

    public InternalNormalJobRuns_45onOneOf1AnyOf4Parser(TokenStream input, NormalJobRuns_45onOneOf1AnyOf4GrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "NormalJobRuns_45onOneOf1AnyOf4";
   	}

   	@Override
   	protected NormalJobRuns_45onOneOf1AnyOf4GrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4
entryRuleNormalJobRuns_45onOneOf1AnyOf4 returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Rule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4=ruleNormalJobRuns_45onOneOf1AnyOf4
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4
ruleNormalJobRuns_45onOneOf1AnyOf4 returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Access().getRuns_45onNormalJobRuns_45onOneOf1AnyOf4AbstractParserRuleCall_0());
			}
			lv_runs_45on_0_0=ruleNormalJobRuns_45onOneOf1AnyOf4Abstract
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Rule());
				}
				set(
					$current,
					"runs_45on",
					lv_runs_45on_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4Abstract");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4Abstract
entryRuleNormalJobRuns_45onOneOf1AnyOf4Abstract returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4Abstract=ruleNormalJobRuns_45onOneOf1AnyOf4Abstract
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4Abstract.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4Abstract
ruleNormalJobRuns_45onOneOf1AnyOf4Abstract returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(ruleNormalJobRuns_45onOneOf1AnyOf4TypeNumber)=>
			{
				newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeNumberParserRuleCall_0());
			}
			this_NormalJobRuns_45onOneOf1AnyOf4TypeNumber_0=ruleNormalJobRuns_45onOneOf1AnyOf4TypeNumber
			{
				$current = $this_NormalJobRuns_45onOneOf1AnyOf4TypeNumber_0.current;
				afterParserOrEnumRuleCall();
			}
		)
		    |
		{
			newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeStringParserRuleCall_1());
		}
		this_NormalJobRuns_45onOneOf1AnyOf4TypeString_1=ruleNormalJobRuns_45onOneOf1AnyOf4TypeString
		{
			$current = $this_NormalJobRuns_45onOneOf1AnyOf4TypeString_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeIntegerParserRuleCall_2());
		}
		this_NormalJobRuns_45onOneOf1AnyOf4TypeInteger_2=ruleNormalJobRuns_45onOneOf1AnyOf4TypeInteger
		{
			$current = $this_NormalJobRuns_45onOneOf1AnyOf4TypeInteger_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeBooleanParserRuleCall_3());
		}
		this_NormalJobRuns_45onOneOf1AnyOf4TypeBoolean_3=ruleNormalJobRuns_45onOneOf1AnyOf4TypeBoolean
		{
			$current = $this_NormalJobRuns_45onOneOf1AnyOf4TypeBoolean_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeObjectParserRuleCall_4());
		}
		this_NormalJobRuns_45onOneOf1AnyOf4TypeObject_4=ruleNormalJobRuns_45onOneOf1AnyOf4TypeObject
		{
			$current = $this_NormalJobRuns_45onOneOf1AnyOf4TypeObject_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeArrayParserRuleCall_5());
		}
		this_NormalJobRuns_45onOneOf1AnyOf4TypeArray_5=ruleNormalJobRuns_45onOneOf1AnyOf4TypeArray
		{
			$current = $this_NormalJobRuns_45onOneOf1AnyOf4TypeArray_5.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeNullParserRuleCall_6());
		}
		this_NormalJobRuns_45onOneOf1AnyOf4TypeNull_6=ruleNormalJobRuns_45onOneOf1AnyOf4TypeNull
		{
			$current = $this_NormalJobRuns_45onOneOf1AnyOf4TypeNull_6.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract
entryRuleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstractRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract=ruleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract
ruleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties)=>
		{
			newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstractAccess().getNormalJobRuns_45onOneOf1AnyOf4AdditionalPropertiesParserRuleCall());
		}
		this_NormalJobRuns_45onOneOf1AnyOf4AdditionalProperties_0=ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties
		{
			$current = $this_NormalJobRuns_45onOneOf1AnyOf4AdditionalProperties_0.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleValue
entryRuleValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getValueRule()); }
	iv_ruleValue=ruleValue
	{ $current=$iv_ruleValue.current; }
	EOF;

// Rule Value
ruleValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getValueAccess().getStringValueParserRuleCall_0());
		}
		this_StringValue_0=ruleStringValue
		{
			$current = $this_StringValue_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getArrayValueParserRuleCall_1());
		}
		this_ArrayValue_1=ruleArrayValue
		{
			$current = $this_ArrayValue_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getNullValueParserRuleCall_2());
		}
		this_NullValue_2=ruleNullValue
		{
			$current = $this_NullValue_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getNumberValueParserRuleCall_3());
		}
		this_NumberValue_3=ruleNumberValue
		{
			$current = $this_NumberValue_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getObjectValueParserRuleCall_4());
		}
		this_ObjectValue_4=ruleObjectValue
		{
			$current = $this_ObjectValue_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getBooleanValueParserRuleCall_5());
		}
		this_BooleanValue_5=ruleBooleanValue
		{
			$current = $this_BooleanValue_5.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeString
entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeString returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeStringRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeString=ruleNormalJobRuns_45onOneOf1AnyOf4TypeString
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeString.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4TypeString
ruleNormalJobRuns_45onOneOf1AnyOf4TypeString returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0=RunsOn
		{
			newLeafNode(otherlv_0, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeStringAccess().getRunsOnKeyword_0());
		}
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeStringAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeStringAccess().getRuns_45onEStringParserRuleCall_2_0());
				}
				lv_runs_45on_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeStringRule());
					}
					set(
						$current,
						"runs_45on",
						lv_runs_45on_2_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeInteger
entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeInteger returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeIntegerRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeInteger=ruleNormalJobRuns_45onOneOf1AnyOf4TypeInteger
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeInteger.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4TypeInteger
ruleNormalJobRuns_45onOneOf1AnyOf4TypeInteger returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0=RunsOn
		{
			newLeafNode(otherlv_0, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeIntegerAccess().getRunsOnKeyword_0());
		}
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeIntegerAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeIntegerAccess().getRuns_45onEDoubleObjectParserRuleCall_2_0());
				}
				lv_runs_45on_2_0=ruleEDoubleObject
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeIntegerRule());
					}
					set(
						$current,
						"runs_45on",
						lv_runs_45on_2_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EDoubleObject");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeNumber
entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeNumber returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNumberRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeNumber=ruleNormalJobRuns_45onOneOf1AnyOf4TypeNumber
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeNumber.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4TypeNumber
ruleNormalJobRuns_45onOneOf1AnyOf4TypeNumber returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0=RunsOn
		{
			newLeafNode(otherlv_0, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNumberAccess().getRunsOnKeyword_0());
		}
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNumberAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNumberAccess().getRuns_45onEDoubleObjectParserRuleCall_2_0());
				}
				lv_runs_45on_2_0=ruleEDoubleObject
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNumberRule());
					}
					set(
						$current,
						"runs_45on",
						lv_runs_45on_2_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EDoubleObject");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeBoolean
entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeBoolean returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeBooleanRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeBoolean=ruleNormalJobRuns_45onOneOf1AnyOf4TypeBoolean
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeBoolean.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4TypeBoolean
ruleNormalJobRuns_45onOneOf1AnyOf4TypeBoolean returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0=RunsOn
		{
			newLeafNode(otherlv_0, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeBooleanAccess().getRunsOnKeyword_0());
		}
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeBooleanAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeBooleanAccess().getRuns_45onEBooleanObjectParserRuleCall_2_0());
				}
				lv_runs_45on_2_0=ruleEBooleanObject
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeBooleanRule());
					}
					set(
						$current,
						"runs_45on",
						lv_runs_45on_2_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EBooleanObject");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeObject
entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeObject returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeObject=ruleNormalJobRuns_45onOneOf1AnyOf4TypeObject
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeObject.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4TypeObject
ruleNormalJobRuns_45onOneOf1AnyOf4TypeObject returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAction_0(),
					$current);
			}
		)
		otherlv_1=RunsOn
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getRunsOnKeyword_1());
		}
		otherlv_2=Colon
		{
			newLeafNode(otherlv_2, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getColonKeyword_2());
		}
		otherlv_3=LeftCurlyBracket
		{
			newLeafNode(otherlv_3, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getRuns_45onNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstractParserRuleCall_4_0_0());
					}
					lv_runs_45on_4_0=ruleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectRule());
						}
						add(
							$current,
							"runs_45on",
							lv_runs_45on_4_0,
							"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_5=Comma
				{
					newLeafNode(otherlv_5, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getCommaKeyword_4_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getRuns_45onNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstractParserRuleCall_4_1_1_0());
						}
						lv_runs_45on_6_0=ruleNormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectRule());
							}
							add(
								$current,
								"runs_45on",
								lv_runs_45on_6_0,
								"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4PropertiesAbstract");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_7=RightCurlyBracket
		{
			newLeafNode(otherlv_7, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeObjectAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeArray
entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeArray returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeArrayRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeArray=ruleNormalJobRuns_45onOneOf1AnyOf4TypeArray
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeArray.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4TypeArray
ruleNormalJobRuns_45onOneOf1AnyOf4TypeArray returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0=RunsOn
		{
			newLeafNode(otherlv_0, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeArrayAccess().getRunsOnKeyword_0());
		}
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeArrayAccess().getColonKeyword_1());
		}
		otherlv_2=LeftSquareBracket
		{
			newLeafNode(otherlv_2, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeArrayAccess().getLeftSquareBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeArrayAccess().getRuns_45onNormalJobRuns_45onOneOf1AnyOf4TupleParserRuleCall_3_0());
				}
				lv_runs_45on_3_0=ruleNormalJobRuns_45onOneOf1AnyOf4Tuple
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeArrayRule());
					}
					set(
						$current,
						"runs_45on",
						lv_runs_45on_3_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4Tuple");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4=RightSquareBracket
		{
			newLeafNode(otherlv_4, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeArrayAccess().getRightSquareBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeNull
entryRuleNormalJobRuns_45onOneOf1AnyOf4TypeNull returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNullRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeNull=ruleNormalJobRuns_45onOneOf1AnyOf4TypeNull
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4TypeNull.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4TypeNull
ruleNormalJobRuns_45onOneOf1AnyOf4TypeNull returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0=RunsOn
		{
			newLeafNode(otherlv_0, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNullAccess().getRunsOnKeyword_0());
		}
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNullAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNullAccess().getRuns_45onNullValueParserRuleCall_2_0());
				}
				lv_runs_45on_2_0=ruleNullValue
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TypeNullRule());
					}
					set(
						$current,
						"runs_45on",
						lv_runs_45on_2_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NullValue");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	{
		newCompositeNode(grammarAccess.getEStringAccess().getVALID_STRINGParserRuleCall());
	}
	this_VALID_STRING_0=ruleVALID_STRING
	{
		$current.merge(this_VALID_STRING_0);
	}
	{
		afterParserOrEnumRuleCall();
	}
;

// Entry rule entryRuleEDoubleObject
entryRuleEDoubleObject returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEDoubleObjectRule()); }
	iv_ruleEDoubleObject=ruleEDoubleObject
	{ $current=$iv_ruleEDoubleObject.current.getText(); }
	EOF;

// Rule EDoubleObject
ruleEDoubleObject returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_E_INT_0=RULE_E_INT
		{
			$current.merge(this_E_INT_0);
		}
		{
			newLeafNode(this_E_INT_0, grammarAccess.getEDoubleObjectAccess().getE_INTTerminalRuleCall_0());
		}
		    |
		this_E_DOUBLE_1=RULE_E_DOUBLE
		{
			$current.merge(this_E_DOUBLE_1);
		}
		{
			newLeafNode(this_E_DOUBLE_1, grammarAccess.getEDoubleObjectAccess().getE_DOUBLETerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleEBooleanObject
entryRuleEBooleanObject returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEBooleanObjectRule()); }
	iv_ruleEBooleanObject=ruleEBooleanObject
	{ $current=$iv_ruleEBooleanObject.current.getText(); }
	EOF;

// Rule EBooleanObject
ruleEBooleanObject returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw=True
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanObjectAccess().getTrueKeyword_0());
		}
		    |
		kw=False
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanObjectAccess().getFalseKeyword_1());
		}
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties
entryRuleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalPropertiesRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties=ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4AdditionalProperties
ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalProperties returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalPropertiesAccess().getKeyEStringParserRuleCall_0_0());
				}
				lv_key_0_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalPropertiesRule());
					}
					set(
						$current,
						"key",
						lv_key_0_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalPropertiesAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalPropertiesAccess().getAdditionalPropertiesJsonDocumentParserRuleCall_2_0());
				}
				lv_additionalProperties_2_0=ruleJsonDocument
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalPropertiesRule());
					}
					set(
						$current,
						"additionalProperties",
						lv_additionalProperties_2_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.JsonDocument");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleJsonDocument
entryRuleJsonDocument returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getJsonDocumentRule()); }
	iv_ruleJsonDocument=ruleJsonDocument
	{ $current=$iv_ruleJsonDocument.current; }
	EOF;

// Rule JsonDocument
ruleJsonDocument returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getJsonDocumentAccess().getValueValueParserRuleCall_0());
			}
			lv_value_0_0=ruleValue
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getJsonDocumentRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.Value");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleStringValue
entryRuleStringValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStringValueRule()); }
	iv_ruleStringValue=ruleStringValue
	{ $current=$iv_ruleStringValue.current; }
	EOF;

// Rule StringValue
ruleStringValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getStringValueAccess().getValueEStringParserRuleCall_0());
			}
			lv_value_0_0=ruleEString
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getStringValueRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EString");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleArrayValue
entryRuleArrayValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getArrayValueRule()); }
	iv_ruleArrayValue=ruleArrayValue
	{ $current=$iv_ruleArrayValue.current; }
	EOF;

// Rule ArrayValue
ruleArrayValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getArrayValueAccess().getArrayValueAction_0(),
					$current);
			}
		)
		otherlv_1=LeftSquareBracket
		{
			newLeafNode(otherlv_1, grammarAccess.getArrayValueAccess().getLeftSquareBracketKeyword_1());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getArrayValueAccess().getValueValueParserRuleCall_2_0_0());
					}
					lv_value_2_0=ruleValue
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getArrayValueRule());
						}
						add(
							$current,
							"value",
							lv_value_2_0,
							"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.Value");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_3=Comma
				{
					newLeafNode(otherlv_3, grammarAccess.getArrayValueAccess().getCommaKeyword_2_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getArrayValueAccess().getValueValueParserRuleCall_2_1_1_0());
						}
						lv_value_4_0=ruleValue
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getArrayValueRule());
							}
							add(
								$current,
								"value",
								lv_value_4_0,
								"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.Value");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_5=RightSquareBracket
		{
			newLeafNode(otherlv_5, grammarAccess.getArrayValueAccess().getRightSquareBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleNullValue
entryRuleNullValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNullValueRule()); }
	iv_ruleNullValue=ruleNullValue
	{ $current=$iv_ruleNullValue.current; }
	EOF;

// Rule NullValue
ruleNullValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getNullValueAccess().getValueNullEnumEnumRuleCall_0());
			}
			lv_value_0_0=ruleNullEnum
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getNullValueRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NullEnum");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleNumberValue
entryRuleNumberValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNumberValueRule()); }
	iv_ruleNumberValue=ruleNumberValue
	{ $current=$iv_ruleNumberValue.current; }
	EOF;

// Rule NumberValue
ruleNumberValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getNumberValueAccess().getValueEDoubleParserRuleCall_0());
			}
			lv_value_0_0=ruleEDouble
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getNumberValueRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EDouble");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleObjectValue
entryRuleObjectValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getObjectValueRule()); }
	iv_ruleObjectValue=ruleObjectValue
	{ $current=$iv_ruleObjectValue.current; }
	EOF;

// Rule ObjectValue
ruleObjectValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getObjectValueAccess().getObjectValueAction_0(),
					$current);
			}
		)
		otherlv_1=LeftCurlyBracket
		{
			newLeafNode(otherlv_1, grammarAccess.getObjectValueAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getObjectValueAccess().getKeyvaluepairKeyValuePairParserRuleCall_2_0_0());
					}
					lv_keyvaluepair_2_0=ruleKeyValuePair
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getObjectValueRule());
						}
						add(
							$current,
							"keyvaluepair",
							lv_keyvaluepair_2_0,
							"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.KeyValuePair");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_3=Comma
				{
					newLeafNode(otherlv_3, grammarAccess.getObjectValueAccess().getCommaKeyword_2_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getObjectValueAccess().getKeyvaluepairKeyValuePairParserRuleCall_2_1_1_0());
						}
						lv_keyvaluepair_4_0=ruleKeyValuePair
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getObjectValueRule());
							}
							add(
								$current,
								"keyvaluepair",
								lv_keyvaluepair_4_0,
								"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.KeyValuePair");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_5=RightCurlyBracket
		{
			newLeafNode(otherlv_5, grammarAccess.getObjectValueAccess().getRightCurlyBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleBooleanValue
entryRuleBooleanValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBooleanValueRule()); }
	iv_ruleBooleanValue=ruleBooleanValue
	{ $current=$iv_ruleBooleanValue.current; }
	EOF;

// Rule BooleanValue
ruleBooleanValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getBooleanValueAccess().getValueEBooleanParserRuleCall_0());
			}
			lv_value_0_0=ruleEBoolean
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getBooleanValueRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EBoolean");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleEDouble
entryRuleEDouble returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEDoubleRule()); }
	iv_ruleEDouble=ruleEDouble
	{ $current=$iv_ruleEDouble.current.getText(); }
	EOF;

// Rule EDouble
ruleEDouble returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_E_INT_0=RULE_E_INT
		{
			$current.merge(this_E_INT_0);
		}
		{
			newLeafNode(this_E_INT_0, grammarAccess.getEDoubleAccess().getE_INTTerminalRuleCall_0());
		}
		    |
		this_E_DOUBLE_1=RULE_E_DOUBLE
		{
			$current.merge(this_E_DOUBLE_1);
		}
		{
			newLeafNode(this_E_DOUBLE_1, grammarAccess.getEDoubleAccess().getE_DOUBLETerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleKeyValuePair
entryRuleKeyValuePair returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getKeyValuePairRule()); }
	iv_ruleKeyValuePair=ruleKeyValuePair
	{ $current=$iv_ruleKeyValuePair.current; }
	EOF;

// Rule KeyValuePair
ruleKeyValuePair returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getKeyValuePairAccess().getKeyEStringParserRuleCall_0_0());
				}
				lv_key_0_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getKeyValuePairRule());
					}
					set(
						$current,
						"key",
						lv_key_0_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1=Colon
		{
			newLeafNode(otherlv_1, grammarAccess.getKeyValuePairAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getKeyValuePairAccess().getValueValueParserRuleCall_2_0());
				}
				lv_value_2_0=ruleValue
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getKeyValuePairRule());
					}
					set(
						$current,
						"value",
						lv_value_2_0,
						"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.Value");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleEBoolean
entryRuleEBoolean returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEBooleanRule()); }
	iv_ruleEBoolean=ruleEBoolean
	{ $current=$iv_ruleEBoolean.current.getText(); }
	EOF;

// Rule EBoolean
ruleEBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw=True
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getTrueKeyword_0());
		}
		    |
		kw=False
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getFalseKeyword_1());
		}
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4Tuple
entryRuleNormalJobRuns_45onOneOf1AnyOf4Tuple returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4Tuple=ruleNormalJobRuns_45onOneOf1AnyOf4Tuple
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4Tuple.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4Tuple
ruleNormalJobRuns_45onOneOf1AnyOf4Tuple returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getNormalJobRuns_45onOneOf1AnyOf4TupleAction_0(),
					$current);
			}
		)
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getItems0NormalJobRuns_45onOneOf1AnyOf4Items0ParserRuleCall_1_0_0());
					}
					lv_items0_1_0=ruleNormalJobRuns_45onOneOf1AnyOf4Items0
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleRule());
						}
						set(
							$current,
							"items0",
							lv_items0_1_0,
							"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4Items0");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_2=Comma
				{
					newLeafNode(otherlv_2, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getCommaKeyword_1_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getItems1NormalJobRuns_45onOneOf1AnyOf4Items1ParserRuleCall_1_1_1_0());
						}
						lv_items1_3_0=ruleNormalJobRuns_45onOneOf1AnyOf4Items1
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleRule());
							}
							set(
								$current,
								"items1",
								lv_items1_3_0,
								"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4Items1");
							afterParserOrEnumRuleCall();
						}
					)
				)
				(
					otherlv_4=Comma
					{
						newLeafNode(otherlv_4, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getCommaKeyword_1_1_2_0());
					}
					(
						(
							{
								newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getItems2NormalJobRuns_45onOneOf1AnyOf4Items2ParserRuleCall_1_1_2_1_0());
							}
							lv_items2_5_0=ruleNormalJobRuns_45onOneOf1AnyOf4Items2
							{
								if ($current==null) {
									$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleRule());
								}
								set(
									$current,
									"items2",
									lv_items2_5_0,
									"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4Items2");
								afterParserOrEnumRuleCall();
							}
						)
					)
					(
						otherlv_6=Comma
						{
							newLeafNode(otherlv_6, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getCommaKeyword_1_1_2_2_0());
						}
						(
							(
								{
									newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getAdditionalItemsNormalJobRuns_45onOneOf1AnyOf4AdditionalItemsParserRuleCall_1_1_2_2_1_0());
								}
								lv_additionalItems_7_0=ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems
								{
									if ($current==null) {
										$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleRule());
									}
									add(
										$current,
										"additionalItems",
										lv_additionalItems_7_0,
										"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4AdditionalItems");
									afterParserOrEnumRuleCall();
								}
							)
						)
						(
							otherlv_8=Comma
							{
								newLeafNode(otherlv_8, grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getCommaKeyword_1_1_2_2_2_0());
							}
							(
								(
									{
										newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleAccess().getAdditionalItemsNormalJobRuns_45onOneOf1AnyOf4AdditionalItemsParserRuleCall_1_1_2_2_2_1_0());
									}
									lv_additionalItems_9_0=ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems
									{
										if ($current==null) {
											$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4TupleRule());
										}
										add(
											$current,
											"additionalItems",
											lv_additionalItems_9_0,
											"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.NormalJobRuns_45onOneOf1AnyOf4AdditionalItems");
										afterParserOrEnumRuleCall();
									}
								)
							)
						)*
					)?
				)?
			)?
		)?
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4Items0
entryRuleNormalJobRuns_45onOneOf1AnyOf4Items0 returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items0Rule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4Items0=ruleNormalJobRuns_45onOneOf1AnyOf4Items0
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4Items0.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4Items0
ruleNormalJobRuns_45onOneOf1AnyOf4Items0 returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items0Access().getItems0JsonDocumentParserRuleCall_0());
			}
			lv_items0_0_0=ruleJsonDocument
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items0Rule());
				}
				set(
					$current,
					"items0",
					lv_items0_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.JsonDocument");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4Items1
entryRuleNormalJobRuns_45onOneOf1AnyOf4Items1 returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items1Rule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4Items1=ruleNormalJobRuns_45onOneOf1AnyOf4Items1
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4Items1.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4Items1
ruleNormalJobRuns_45onOneOf1AnyOf4Items1 returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items1Access().getItems1ArchitectureParserRuleCall_0());
			}
			lv_items1_0_0=ruleArchitecture
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items1Rule());
				}
				set(
					$current,
					"items1",
					lv_items1_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.Architecture");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4Items2
entryRuleNormalJobRuns_45onOneOf1AnyOf4Items2 returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items2Rule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4Items2=ruleNormalJobRuns_45onOneOf1AnyOf4Items2
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4Items2.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4Items2
ruleNormalJobRuns_45onOneOf1AnyOf4Items2 returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items2Access().getItems2MachineParserRuleCall_0());
			}
			lv_items2_0_0=ruleMachine
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4Items2Rule());
				}
				set(
					$current,
					"items2",
					lv_items2_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.Machine");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems
entryRuleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalItemsRule()); }
	iv_ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems=ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems
	{ $current=$iv_ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems.current; }
	EOF;

// Rule NormalJobRuns_45onOneOf1AnyOf4AdditionalItems
ruleNormalJobRuns_45onOneOf1AnyOf4AdditionalItems returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalItemsAccess().getAdditionalItemsEStringParserRuleCall_0());
			}
			lv_additionalItems_0_0=ruleEString
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getNormalJobRuns_45onOneOf1AnyOf4AdditionalItemsRule());
				}
				set(
					$current,
					"additionalItems",
					lv_additionalItems_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.EString");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleArchitecture
entryRuleArchitecture returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getArchitectureRule()); }
	iv_ruleArchitecture=ruleArchitecture
	{ $current=$iv_ruleArchitecture.current; }
	EOF;

// Rule Architecture
ruleArchitecture returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getArchitectureAccess().getArchitectureJsonDocumentParserRuleCall_0());
			}
			lv_architecture_0_0=ruleJsonDocument
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getArchitectureRule());
				}
				set(
					$current,
					"architecture",
					lv_architecture_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.JsonDocument");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleMachine
entryRuleMachine returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMachineRule()); }
	iv_ruleMachine=ruleMachine
	{ $current=$iv_ruleMachine.current; }
	EOF;

// Rule Machine
ruleMachine returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getMachineAccess().getMachineJsonDocumentParserRuleCall_0());
			}
			lv_machine_0_0=ruleJsonDocument
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getMachineRule());
				}
				set(
					$current,
					"machine",
					lv_machine_0_0,
					"githubwf.githubwf.NormalJobRuns_45onOneOf1AnyOf4.JsonDocument");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleVALID_STRING
entryRuleVALID_STRING returns [String current=null]:
	{ newCompositeNode(grammarAccess.getVALID_STRINGRule()); }
	iv_ruleVALID_STRING=ruleVALID_STRING
	{ $current=$iv_ruleVALID_STRING.current.getText(); }
	EOF;

// Rule VALID_STRING
ruleVALID_STRING returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getVALID_STRINGAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		{
			newCompositeNode(grammarAccess.getVALID_STRINGAccess().getKEYWORDParserRuleCall_1());
		}
		this_KEYWORD_1=ruleKEYWORD
		{
			$current.merge(this_KEYWORD_1);
		}
		{
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleKEYWORD
entryRuleKEYWORD returns [String current=null]:
	{ newCompositeNode(grammarAccess.getKEYWORDRule()); }
	iv_ruleKEYWORD=ruleKEYWORD
	{ $current=$iv_ruleKEYWORD.current.getText(); }
	EOF;

// Rule KEYWORD
ruleKEYWORD returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	kw=RunsOn
	{
		$current.merge(kw);
		newLeafNode(kw, grammarAccess.getKEYWORDAccess().getRunsOnKeyword());
	}
;

// Rule NullEnum
ruleNullEnum returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		enumLiteral_0=Null
		{
			$current = grammarAccess.getNullEnumAccess().getNullEnumLiteralDeclaration().getEnumLiteral().getInstance();
			newLeafNode(enumLiteral_0, grammarAccess.getNullEnumAccess().getNullEnumLiteralDeclaration());
		}
	)
;
