/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ContainerPortsItemsOneOf1StandaloneSetup extends ContainerPortsItemsOneOf1StandaloneSetupGenerated {

	public static void doSetup() {
		new ContainerPortsItemsOneOf1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
