/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GithubwfRootConcurrencyOneOf1StandaloneSetup extends GithubwfRootConcurrencyOneOf1StandaloneSetupGenerated {

	public static void doSetup() {
		new GithubwfRootConcurrencyOneOf1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
