/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1IfStandaloneSetup extends GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1IfStandaloneSetupGenerated {

	public static void doSetup() {
		new GithubwfRootOnOneOf2Workflow_dispatchInputsPatternProperties0AllOf1IfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
