/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NormalJobConcurrencyOneOf1StandaloneSetup extends NormalJobConcurrencyOneOf1StandaloneSetupGenerated {

	public static void doSetup() {
		new NormalJobConcurrencyOneOf1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
