/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf1StandaloneSetup extends NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf1StandaloneSetupGenerated {

	public static void doSetup() {
		new NormalJobStepsItemsAllOf1Continue_45on_45errorOneOf1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
