/*
 * generated by Xtext 2.23.0
 */
package githubwf.githubwf;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NormalJobStepsItemsAllOf0OneOf0RuntimeModule extends AbstractNormalJobStepsItemsAllOf0OneOf0RuntimeModule {
}
