/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ReusableWorkflowCallJobConcurrencyOneOf0StandaloneSetup extends ReusableWorkflowCallJobConcurrencyOneOf0StandaloneSetupGenerated {

	public static void doSetup() {
		new ReusableWorkflowCallJobConcurrencyOneOf0StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
