/*
 * generated by Xtext 2.29.0
 */
package githubwf.githubwf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ShellAnyOf0StandaloneSetup extends ShellAnyOf0StandaloneSetupGenerated {

	public static void doSetup() {
		new ShellAnyOf0StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
